# Generated by Django 4.0 on 2023-02-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('emne', models.CharField(max_length=200)),
                ('melding', models.TextField(max_length=1500)),
            ],
        ),
    ]
