# Generated by Django 4.0 on 2023-02-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='problems.state'),
            preserve_default=False,
        ),
    ]
