# Generated by Django 4.0 on 2023-02-08 11:16

from django.db import migrations, models
import django.db.models.deletion
import problems.models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_ticket_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='state',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(blank=True, default=problems.models.get_default_status, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.status'),
        ),
    ]
