# Generated by Django 4.0 on 2023-03-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_kategori_tekst_farge_underkategori_tekst_farge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategori',
            old_name='tekst_farge',
            new_name='tekst_hvit',
        ),
        migrations.RenameField(
            model_name='underkategori',
            old_name='tekst_farge',
            new_name='tekst_hvit',
        ),
    ]
