# Generated by Django 4.0 on 2023-03-06 09:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_rename_tekst_farge_kategori_tekst_hvit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='tekst_hvit',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='underkategori',
            name='tekst_hvit',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
    ]
