# Generated by Django 4.0 on 2023-03-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_alter_kategori_tekst_hvit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategori',
            old_name='tekst_hvit',
            new_name='tekst_farge',
        ),
        migrations.RenameField(
            model_name='underkategori',
            old_name='tekst_hvit',
            new_name='tekst_farge',
        ),
    ]
