# Generated by Django 4.0 on 2023-01-16 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('navn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('farge', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='UnderKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=70)),
                ('farge', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('tittel', models.CharField(max_length=200)),
                ('beskrivelse', models.CharField(max_length=1000)),
                ('guide', models.TextField(max_length=20000)),
                ('dato_postet', models.DateField(default=datetime.date.today)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.kategori')),
            ],
        ),
        migrations.AddField(
            model_name='kategori',
            name='under_kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.underkategori'),
        ),
    ]
