# Generated by Django 4.0 on 2023-01-18 09:25

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.IntegerField(default=pages.models.generate_id),
        ),
    ]
