# Generated by Django 4.0 on 2023-01-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_problem_id_alter_problem_problem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='dato_postet',
        ),
    ]
